version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  admin:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
